# Generated by Django 3.1.7 on 2021-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=30)),
                ('bse_script_code', models.CharField(max_length=30)),
                ('bse_house_code', models.CharField(max_length=30)),
                ('stock_flag', models.CharField(max_length=5)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('market_cap_str', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
