# Generated by Django 3.1.7 on 2021-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockant_Danesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_flag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
