# Generated by Django 3.1.7 on 2021-04-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockant_Danesh', '0003_recommendation_stockprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprice',
            old_name='data',
            new_name='date',
        ),
    ]
