# Generated by Django 3.1.7 on 2021-04-27 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockant_Danesh', '0004_auto_20210427_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='result_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='horizon',
            field=models.CharField(choices=[('b', 'Buy'), ('s', 'Sell'), ('h', 'Hold')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='period',
            field=models.CharField(choices=[('w', 'Week'), ('m', 'Month'), ('q', 'Quarter')], max_length=30),
        ),
    ]
