# Generated by Django 3.1.7 on 2021-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockant_Danesh', '0007_recommendation_result_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
